version: "3"
services: 
    react-app:
        container_name: react_container
        build: 
            context: ./music-app
            dockerfile: react-app
        ports: 
            - 3000:3000
        volumes: 
            - ".:/app"
            - "/app/node_modules"
        environment: 
            - NODE_ENV=development
        stdin_open: true
    loginserver:
        container_name: nodeLogin
        build: 
            context: ./loginDataServer
            dockerfile: loginDataServer
        ports: 
            - 8080:8080
        environment: 
            - NODE_ENV=development