version: '3'

services:
  # proxy:
  #   image: nginx
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./Streaming/html/:/usr/share/nginx/html/:ro
  web-app:
    build: 
      context: ./Streaming/React/
    image: rasje17/music-app
    ports: 
      - '3000:3000'
    restart: on-failure
    volumes: 
      - ./Streaming/React/music-app:/app
    container_name: web-app
    tty: true